In [1]:
import numpy as np

# numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
np.array(benimListem)

array([20, 30, 40])

In [4]:
matrixListesi = [[10,20,30],[40,50,60],[70,80,90]]

In [5]:
np.array(matrixListesi)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# arange

In [6]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# zeros

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# linspace

In [13]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [14]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# eye

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# random

In [16]:
np.random.randn(5)

array([ 0.59917805,  0.35598562, -1.00736359,  0.72130743, -0.20564234])

In [17]:
np.random.randn(4,4)

array([[ 0.25255704, -0.84850985,  0.20453108,  0.27937095],
       [-0.22138806, -0.52545268, -0.78873876,  0.4714071 ],
       [ 0.16827498,  0.2428944 ,  0.93146598,  0.77478334],
       [-1.1333887 ,  1.35462038,  1.83077623,  1.86732526]])

In [18]:
np.random.randint(1,20)

6

In [19]:
np.random.randint(1,100,5)

array([47, 55, 20, 54, 38])

In [20]:
benimNumpyDizim = np.arange(20)

In [21]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
benimRandomDizim = np.random.randint(0,100,20)

In [23]:
benimRandomDizim

array([11, 58, 15, 22,  3, 50, 16, 26,  3, 47,  8, 21, 19, 60, 75,  2, 40,
       90, 80, 38])

# Numpy Dizi Methodları

In [24]:
benimNumpyDizim.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
benimRandomDizim.max()

90

In [26]:
benimRandomDizim.min()

2

In [27]:
benimRandomDizim.argmax()

17

In [28]:
benimRandomDizim.argmin()

15

In [30]:
reshapeDizim = benimNumpyDizim.reshape(4,5)

In [31]:
reshapeDizim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
reshapeDizim.shape

(4, 5)