In [24]:
import numpy as np

In [25]:
benimDizim = np.arange(0,15)

In [26]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
benimDizim[5]

5

In [28]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [29]:
benimDizim[5:10] = -5

In [30]:
benimDizim

array([ 0,  1,  2,  3,  4, -5, -5, -5, -5, -5, 10, 11, 12, 13, 14])

In [31]:
baskaDizi = np.arange(0,24)

In [32]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
baskaDizi[4:9]

array([4, 5, 6, 7, 8])

In [34]:
slicingDizisi = baskaDizi[4:9]

In [35]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [36]:
slicingDizisi[:] = 700

In [37]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [38]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [39]:
# asıl liste kalsın, benim aldığım kısım değişsin diyorsan;

In [41]:
ornekDizi = np.arange(0,24)

In [42]:
ornekDiziKopyasi = ornekDizi.copy()

In [43]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [44]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[4:9]

In [46]:
ornekDiziKopyasiSlicing

array([4, 5, 6, 7, 8])

In [47]:
ornekDiziKopyasiSlicing[:] = 800

In [48]:
ornekDiziKopyasi

array([  0,   1,   2,   3, 800, 800, 800, 800, 800,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [49]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# matrix

In [54]:
benimListem = [[10,20,30],[40,50,60],[70,80,90]]

In [55]:
benimMatrixListem = np.array(benimListem)

In [56]:
benimMatrixListem

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [57]:
benimMatrixListem[0]

array([10, 20, 30])

In [58]:
benimMatrixListem[1][1]

50

In [59]:
benimMatrixListem[1,1]

50

In [60]:
#slicing yapabilirim (değiştirme)

In [63]:
benimMatrixListem[0:,1]

array([20, 50, 80])

In [64]:
benimMatrixListem[0:,0]

array([10, 40, 70])

In [66]:
benimMatrixListem[0:,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [67]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [68]:
yeniMatrix = np.array(yeniListe)

In [69]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
yeniMatrix[[1,3]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [71]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# operasyonlar

In [72]:
yeniBirDizi = np.random.randint(1,100,20)

In [73]:
yeniBirDizi

array([55, 96, 86, 30, 69, 82,  8,  4, 92, 39, 27, 81, 60, 68, 24, 71, 60,
       65, 56, 67])

In [74]:
yeniBirDizi >50

array([ True,  True,  True, False,  True,  True, False, False,  True,
       False, False,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [75]:
sonucDizisi = yeniBirDizi >50

In [76]:
sonucDizisi

array([ True,  True,  True, False,  True,  True, False, False,  True,
       False, False,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [78]:
yeniBirDizi[sonucDizisi]

array([55, 96, 86, 69, 82, 92, 81, 60, 68, 71, 60, 65, 56, 67])

In [79]:
yeniBirDizi [yeniBirDizi >50]

array([55, 96, 86, 69, 82, 92, 81, 60, 68, 71, 60, 65, 56, 67])

In [80]:
sonDizi = np.arange(0,25)

In [81]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [83]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [84]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])